const routes = {
    home: '/',
    laptop: '/laptop',
    msi: '/msi',
    acer: '/acer',
    asus: '/asus',
    search: '/search',
    login: 'login',
    product: '/laptop/:product',
    profile: '/@:nickname',
    addressProfile: '/@:nickname/address-shipping',
    shoppingCart: '/@:nickname/shopping-cart',
    checkout: '/@:nickname/checkout',
    admin: '/admin',
    adminUsers: '/admin/users',
    adminManagers: '/admin/managers',
    adminCategory: '/admin/category',
    adminProduct: '/admin/product',
    adminAddProduct: '/admin/product/:idproduct',
    adminUpdateBrand: '/admin/category/:idbrand',
    adminSlider: '/admin/slider',
    adminBill: '/admin/bill',
    adminViewBill: '/admin/bill/:idbill',
    adminStock: '/admin/stock',
    adminProfileInfo: '/admin/profileinfo',
};

export default routes;
